name: anyscale-academy
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.8
  - pip
  - pandas
  - holoviews
  - bokeh
  - psutil
  - jupyterlab
  - jupyter-server-proxy
  - beautifulsoup4
  - lxml
  - setproctitle
  - pytz
  - pip:
    - ray[rllib]==0.8.4
    - atoma
