name: anyscale-academy
channels:
    - conda-forge
    - pyviz
dependencies:
  - python=3.8
  - pip
  - bokeh
  - ipywidgets
  - holoviz
  - psutil
  - jupyterlab
  - jupyter-server-proxy
  - pip:
    - ray[rllib]==0.8.4
    - numpy
    - matplotlib
    - bs4
    - lxml
    - scikit-learn
    - setproctitle
    - atoma
    - pytz
