name: anyscale-academy
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.7
  - pip
  - pandas
  - requests
  - pytorch
  - tensorflow
  - keras
  - scikit-learn
  - holoviews
  - bokeh
  - ipywidgets
  - psutil
  - jupyterlab
  - jupyter-server-proxy
  - beautifulsoup4
  - lxml
  - setproctitle
  - pytz
  - nodejs
  - pip:
    - ray[rllib]==0.8.5
    - ray[tune]==0.8.5
    - ray[debug]==0.8.5
    - atoma
    - anyscale

