name: anyscale-academy
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.7
  - pip
  - pandas
  - requests
  - tensorflow
  - keras
  - holoviews
  - bokeh
  - ipywidgets
  - psutil
  - jupyterlab
  - jupyter-server-proxy
  - beautifulsoup4
  - lxml
  - setproctitle
  - pytz
  - pip:
    - ray[rllib]==0.8.4
    - ray[tune]==0.8.4
    - ray[debug]==0.8.4
    - atoma

